### ISSUE TITLE
[MJAVADOC-742] [REGRESSION] Transitive dependencies of docletArtifact missing

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-javadoc-plugin#1122]
**[Patrick Ruckstuhl](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=tario)** opened **[MJAVADOC-742](https://issues.apache.org/jira/browse/MJAVADOC-742?redirect=false)** and commented

It looks like with 3.5.0 transitive dependencies of the docletArtifact are no longer added to the classpath and generation fails with class not found. Reverting back to 3.4.1 everything works fine.

---

**Affects:** 3.5.0

**Issue Links:**
- [MJAVADOC-731](https://issues.apache.org/jira/browse/MJAVADOC-731) Migrate components to JSR 330, get rid of maven-artifact-transfer, update to parent 37
 (_**"is caused by"**_)

**Remote Links:**
- [GitHub Pull Request #186
](https://github.com/apache/maven-javadoc-plugin/pull/186)

1 votes, 7 watchers

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

Can you bisect to the offending change and provide a test case?

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

I am certain that MJAVADOC-731 causes the issue. [Konrad Windszus](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kwin), can you check this when a reproducer is provided?

**Comment by jira-importer** [comment]
**[Patrick Ruckstuhl](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=tario)** commented

```
8b589325762280cef9ff8df2bc3431d4fccafbc7 is the first bad commit
commit 8b589325762280cef9ff8df2bc3431d4fccafbc7
Author: Konrad Windszus <kwin@apache.org>
Date:   Tue Sep 27 14:20:42 2022 +0200
    MJAVADOC-731 Update parent, get rid of legacy (#164)
    Remove legacy plexus component annotations
    Remove usage of m-artifact-transfer and directly leverage m-resolver API
    Mark Maven Core plugins as provided dependencies
 pom.xml                                            |  50 ++---
 .../maven/plugins/javadoc/AbstractJavadocMojo.java | 218 +++++++++++----------
 .../maven/plugins/javadoc/TestJavadocJar.java      |  12 +-
 .../maven/plugins/javadoc/TestJavadocReport.java   |  12 +-
 .../plugins/javadoc/resolver/ResourceResolver.java |  95 +++++----
 .../javadoc/AggregatorJavadocReportTest.java       |   2 +-
 .../maven/plugins/javadoc/JavadocReportTest.java   |  17 +-
 .../stubs/TagletArtifactsMavenProjectStub.java     |  18 +-
 8 files changed, 217 insertions(+), 207 deletions(-)
```

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

[Tamas Cservenak](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cstamas), any ideas?

**Comment by jira-importer** [comment]
**[Patrick Ruckstuhl](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=tario)** commented

I created a simple reproduction here: https://github.com/tarioch/MJAVADOC-742 it uses freemarker as the "failing transitive dependency" but you can use anything.

**Comment by jira-importer** [comment]
**[Konrad Windszus](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kwin)** commented

I tried to first install the doclet from the reproducer repo mentioned above into the local repo and afterwards executed the `project` with `mvn javadoc:javadoc`.
With both m-javadoc- 3.5.0 and 3.4.1 I run into

```
[INFO] --- javadoc:3.4.1:javadoc (default-cli) @ project ---
[WARNING] Source files encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[INFO] No previous run data found, generating javadoc.
[INFO] 
2 errors
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.900 s
[INFO] Finished at: 2023-02-19T22:10:09+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.4.1:javadoc (default-cli) on project project: An error has occurred in Javadoc report generation: 
[ERROR] Exit code: 4 - javadoc: error - fatal error encountered: java.lang.NullPointerException
[ERROR] javadoc: error - Please file a bug against the javadoc tool via the Java bug reporting page
[ERROR] (http://bugreport.java.com) after checking the Bug Database (http://bugs.java.com)
[ERROR] for duplicates. Include error messages and the following diagnostic in your report. Thank you.
[ERROR] java.lang.NullPointerException
[ERROR] 	at jdk.javadoc/jdk.javadoc.internal.tool.Start.handleDocletOptions(Start.java:634)
[ERROR] 	at jdk.javadoc/jdk.javadoc.internal.tool.Start.parseArgs(Start.java:806)
[ERROR] 	at jdk.javadoc/jdk.javadoc.internal.tool.Start.parseAndExecute(Start.java:529)
[ERROR] 	at jdk.javadoc/jdk.javadoc.internal.tool.Start.begin(Start.java:432)
[ERROR] 	at jdk.javadoc/jdk.javadoc.internal.tool.Start.begin(Start.java:345)
[ERROR] 	at jdk.javadoc/jdk.javadoc.internal.tool.Main.execute(Main.java:63)
[ERROR] 	at jdk.javadoc/jdk.javadoc.internal.tool.Main.main(Main.java:52)
[ERROR] 
[ERROR] Command line was: /Library/Java/JavaVirtualMachines/temurin-11.jdk/Contents/Home/bin/javadoc @options @argfile
[ERROR] 
[ERROR] Refer to the generated Javadoc files in '/Users/konradwindszus/git/maven/MJAVADOC-742/project/target/site/apidocs' dir.
[ERROR] 
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

This happens with

```
mvn --version
Apache Maven 3.9.0 (9b58d2bad23a66be161c4664ef21ce219c2c8584)
Maven home: /opt/homebrew/Cellar/maven/3.9.0/libexec
Java version: 11.0.18, vendor: Eclipse Adoptium, runtime: /Library/Java/JavaVirtualMachines/temurin-11.jdk/Contents/Home
Default locale: en_DE, platform encoding: UTF-8
OS name: "mac os x", version: "12.6.3", arch: "aarch64", family: "mac"
```

[Patrick Ruckstuhl](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=tario) Which error message do you see with which JDK and Maven version?

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

Same problem where with:

```
C:\Users\mosipov\MJAVADOC-742\project [master ≡]> mvn -v
Apache Maven 3.8.7 (b89d5959fcde851dcb1c8946a785a163f14e1e29)
Maven home: D:\Entwicklung\Programme\apache-maven-3.8.7
Java version: 11.0.14, vendor: Eclipse Adoptium, runtime: C:\Program Files\Eclipse Adoptium\jdk-11.0.14.9-hotspot
Default locale: de_DE, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
```

**Comment by jira-importer** [comment]
**[Patrick Ruckstuhl](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=tario)** commented

```java
mvn javadoc:javadoc
[INFO] Scanning for projects...
[INFO]
[INFO] -------------------< org.tario.MJAVADOC-742:project >-------------------
[INFO] Building project 0.0.1-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] >>> maven-javadoc-plugin:3.5.0:javadoc (default-cli) > generate-sources @ project >>>
[INFO]
[INFO] <<< maven-javadoc-plugin:3.5.0:javadoc (default-cli) < generate-sources @ project <<<
[INFO]
[INFO]
[INFO] --- maven-javadoc-plugin:3.5.0:javadoc (default-cli) @ project ---
Downloading from apexcollateral: https://artifactory.fis.dev/artifactory/apexcoll-maven-dev/org/tario/MJAVADOC-742/doclet/0.0.1-SNAPSHOT/maven-metadata.xml
[WARNING] Source files encoding has not been set, using platform encoding Cp1252, i.e. build is platform dependent!
[INFO] Configuration changed, re-generating javadoc.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  3.233 s
[INFO] Finished at: 2023-02-20T07:58:26+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.5.0:javadoc (default-cli) on project project: An error has occurred in Javadoc report generation:
[ERROR] Exit code: 4
[ERROR] error: fatal error encountered: java.lang.NoClassDefFoundError: freemarker/template/Configuration
[ERROR] error: Please file a bug against the javadoc tool via the Java bug reporting page
[ERROR]   (http://bugreport.java.com) after checking the Bug Database (http://bugs.java.com)
[ERROR]   for duplicates. Include error messages and the following diagnostic in your report. Thank you.
[ERROR] java.lang.NoClassDefFoundError: freemarker/template/Configuration
[ERROR]         at DummyDoclet.run(DummyDoclet.java:33)
[ERROR]         at jdk.javadoc/jdk.javadoc.internal.tool.Start.parseAndExecute(Start.java:556)
[ERROR]         at jdk.javadoc/jdk.javadoc.internal.tool.Start.begin(Start.java:393)
[ERROR]         at jdk.javadoc/jdk.javadoc.internal.tool.Start.begin(Start.java:342)
[ERROR]         at jdk.javadoc/jdk.javadoc.internal.tool.Main.execute(Main.java:63)
[ERROR]         at jdk.javadoc/jdk.javadoc.internal.tool.Main.main(Main.java:52)
[ERROR] Caused by: java.lang.ClassNotFoundException: freemarker.template.Configuration
[ERROR]         at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
[ERROR]         at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
[ERROR]         at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[ERROR]         ... 6 more
[ERROR] 2 errors
[ERROR] Command line was: cmd.exe /X /C ""C:\Program Files\Eclipse Adoptium\jdk-17.0.5.8-hotspot\bin\javadoc.exe" @options @argfile"
[ERROR]
[ERROR] Refer to the generated Javadoc files in 'E:\projects\workspaces\playground\MJAVADOC-742\project\target\site\apidocs' dir.
[ERROR]
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException 
```

With

```java
mvn -v
Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537)
Maven home: C:\ProgramData\chocolatey\lib\maven\apache-maven-3.8.4
Java version: 17.0.5, vendor: Eclipse Adoptium, runtime: C:\Program Files\Eclipse Adoptium\jdk-17.0.5.8-hotspot
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows" 
```

**Comment by jira-importer** [comment]
**[Patrick Ruckstuhl](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=tario)** commented

Also now tried with latest maven

```
..\apache-maven-3.9.0\bin\mvn --version
Apache Maven 3.9.0 (9b58d2bad23a66be161c4664ef21ce219c2c8584)
Maven home: E:\projects\workspaces\playground\MJAVADOC-742\apache-maven-3.9.0
Java version: 17.0.5, vendor: Eclipse Adoptium, runtime: C:\Program Files\Eclipse Adoptium\jdk-17.0.5.8-hotspot
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows" 
```

and still same result. But if I use java 11, then I get your result. So it looks like a different behavior with Java 17.

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

I think there are several issues here which need to be addressed:

1. The NPE with the old version (3.4.1), this cannot be a regression
2. The CNFE with Java 17 from old to new version

[Patrick Ruckstuhl](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=tario), Maven 3.8.4 has been superseded, **don't** use it.

**Comment by jira-importer** [comment]
**[Peter Verhas](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=peter@verhas.com)** commented

I also got into this issue with my https://github.com/verhas/jamal project. In this case, I could get to the point that I could see that version 3.4.1 generates an `options` file with

```

'/Users/verhasp/.m2/repository/com/javax0/jamal/jamal-doclet/1.12.6/jamal-doclet-1.12.6.jar:/Users/verhasp/.m2/repository/com/javax0/jamal/jamal-api/1.12.6/jamal-api-1.12.6.jar:/Users/verhasp/.m2/repository/com/javax0/jamal/jamal-tools/1.12.6/jamal-tools-1.12.6.jar:/Users/verhasp/.m2/repository/com/javax0/levenshtein/1.0.0/levenshtein-1.0.0.jar:/Users/verhasp/.m2/repository/com/javax0/jamal/jamal-engine/1.12.6/jamal-engine-1.12.6.jar:/Users/verhasp/.m2/repository/com/javax0/jamal/jamal-core/1.12.6/jamal-core-1.12.6.jar'

```

 

The same `options` file generated by the plugin 3.5.0 contains

```

'/Users/verhasp/.m2/repository/com/javax0/jamal/jamal-doclet/1.12.6/jamal-doclet-1.12.6.jar'

```

 

The missing JARs are those are the transitive dependencies of the doclet artifact.

 

When you fix this issue pay attention to do the same for the `-tagletpath` option as well. It suffers from the same issue.

 

A possible workaround (not tried) is to add all the dependencies to the POM file.

**Comment by jira-importer** [comment]
**[Tamas Cservenak](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cstamas)** commented

Unsure about NPE, but this PR fixes doclet resolution https://github.com/apache/maven-javadoc-plugin/pull/186

**Comment by jira-importer** [comment]
**[Konrad Windszus](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kwin)** commented

The NPE observed with the reproducer provided above on JDK < 17 happens here: https://github.com/openjdk/jdk11u-dev/blob/bcce7afba4503e3bc9f1d7dc2aa7de7eca86c764/src/jdk.javadoc/share/classes/jdk/javadoc/internal/tool/Start.java#L634C34-L634C47. So `doclet.getSupportedOptions()` obviously returns `null`. According to https://github.com/openjdk/jdk11u-dev/blob/bcce7afba4503e3bc9f1d7dc2aa7de7eca86c764/src/jdk.javadoc/share/classes/jdk/javadoc/doclet/Doclet.java#L86C27-L86C46 null must never be returned there but it does in https://github.com/tarioch/MJAVADOC-742/blob/18ac22d5073dde43800c341f74fc7fd2b96b85f8/doclet/src/main/java/DummyDoclet.java#L28. So this NPE is clearly an implementation bug with the reproducer.

Not sure yet, why with JDK 17 this doesn't run into the NPE.

**Comment by jira-importer** [comment]
**[Konrad Windszus](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kwin)** commented

Fixed in https://github.com/apache/maven-javadoc-plugin/commit/24362d288bc70c658cdcced4cc0b60b648180dc7.
