### ISSUE TITLE
[MJAVADOC-749] Encounter fatal error while updating javadoc-plugin from 3.2.0 to 3.3.2

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-javadoc-plugin#1131]
**[Zhangjian He](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=shoothzj)** opened **[MJAVADOC-749](https://issues.apache.org/jira/browse/MJAVADOC-749?redirect=false)** and commented

When updating Apache bookkeeper's  javadoc-plugin from 3.2.0 to 3.3.2. the pr link is here: https://github.com/apache/bookkeeper/pull/3852

And the configuration is:

```
<plugin>
<groupId>org.apache.maven.plugins</groupId>
<artifactId>maven-javadoc-plugin</artifactId>
<version>${maven-javadoc-plugin.version}</version>
<configuration>
<source>${javac.target}</source>
<notimestamp>true</notimestamp>
<!-- Prevent missing javadoc comments from being marked as errors -->
<doclint>none</doclint>
<subpackages>org.apache.bookkeeper.client:org.apache.bookkeeper.client.api:org.apache.bookkeeper.common.annotation:org.apache.bookkeeper.conf:org.apache.bookkeeper.feature:org.apache.bookkeeper.stats</subpackages>
<groups>
<group>
<title>Bookkeeper Client</title>
<packages>org.apache.bookkeeper.client:org.apache.bookkeeper.common.annotation:org.apache.bookkeeper.conf:org.apache.bookkeeper.feature</packages>
</group>
<group>
<title>Bookkeeper Client (New Fluent API - Experimental)</title>
<packages>org.apache.bookkeeper.client.api</packages>
</group>
<group>
<title>Bookkeeper Stats API</title>
<packages>org.apache.bookkeeper.stats</packages>
</group>
<group>
<title>Bookkeeper Stats Providers</title>
<packages>org.apache.bookkeeper.stats.codahale:org.apache.bookkeeper.stats.prometheus</packages>
</group>
</groups>
<doctitle>BookKeeper Java API (version ${project.version})</doctitle>
<overview>site/_site/overview/index.html</overview>
<show>package</show>
<detectJavaApiLink>false</detectJavaApiLink>
<!-- The javadoc plugin only runs in the javadoc modules. But with the default configuration it tries
to run a new maven instance in every dependency, in order to generate the apidocs there as well.
{@link https://maven.apache.org/plugins-archives/maven-javadoc-plugin-3.1.1/javadoc-mojo.html#detectOfflineLinks} -->
<detectOfflineLinks>false</detectOfflineLinks>
</configuration>
<executions>
<execution>
<id>aggregate</id>
<goals>
<goal>aggregate</goal>
</goals>
<phase>site</phase>
</execution>
</executions>
</plugin>
```

Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.3.2:jar (attach-javadocs) on project bookkeeper-stats-api: MavenReportException: Error while generating Javadoc:  Error:  Exit code: 4 - javadoc: error - fatal error encountered: java.lang.AssertionError

[ERROR] java.lang.AssertionError
[ERROR]         at jdk.compiler/com.sun.tools.javac.util.Assert.error(Assert.java:155)
[ERROR]         at jdk.compiler/com.sun.tools.javac.util.Assert.checkNonNull(Assert.java:62)
[ERROR]         at jdk.compiler/com.sun.tools.javac.comp.Modules.allModules(Modules.java:1216)
[ERROR]         at jdk.javadoc/jdk.javadoc.internal.tool.ElementsTable.findModuleOfPackageName(ElementsTable.java:857)
[ERROR]         at jdk.javadoc/jdk.javadoc.internal.tool.ElementsTable.addPackagesFromLocations(ElementsTable.java:537)
[ERROR]         at jdk.javadoc/jdk.javadoc.internal.tool.ElementsTable.computeSubpackages(ElementsTable.java:510)
[ERROR]         at jdk.javadoc/jdk.javadoc.internal.tool.ElementsTable.computeSpecifiedPackages(ElementsTable.java:747)
[ERROR]         at jdk.javadoc/jdk.javadoc.internal.tool.ElementsTable.analyze(ElementsTable.java:347)
[ERROR]         at jdk.javadoc/jdk.javadoc.internal.tool.JavadocTool.getEnvironment(JavadocTool.java:220)
[ERROR]         at jdk.javadoc/jdk.javadoc.internal.tool.Start.parseAndExecute(Start.java:546)
[ERROR]         at jdk.javadoc/jdk.javadoc.internal.tool.Start.begin(Start.java:393)
[ERROR]         at jdk.javadoc/jdk.javadoc.internal.tool.Start.begin(Start.java:342)
[ERROR]         at jdk.javadoc/jdk.javadoc.internal.tool.Main.execute(Main.java:63)
[ERROR]         at jdk.javadoc/jdk.javadoc.internal.tool.Main.main(Main.java:52)
[ERROR] 2 个错误
[ERROR] 
[ERROR] Command line was: /Library/Java/JavaVirtualMachines/jdk-17.0.1.jdk/Contents/Home/bin/javadoc `@options`

 

---

**Affects:** 3.3.2

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

Can you bisect to the first failing commit?

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

Ping!

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

No reaction for more than a year.
