### ISSUE TITLE
[MJAVADOC-14] javadoc:javadoc fails with ioexception on Mac OSX due to wrong path to javadoc command.

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-javadoc-plugin#450]
**[Dave Sag](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=davesag)** opened **[MJAVADOC-14](https://issues.apache.org/jira/browse/MJAVADOC-14?redirect=false)** and commented

The javadoc:javadoc plugin has started failing on my Mac since the release of beta 3 of m2.

the stacktrace is as follows:

[INFO] ----------------------------------------------------------------------------
[INFO] Diagnosis: An error has occurred in JavaDocs report generation.
[INFO] ----------------------------------------------------------------------------
[DEBUG] Trace:

org.apache.maven.plugin.MojoExecutionException: An error has occurred in JavaDocs report generation.
at org.apache.maven.reporting.AbstractMavenReport.execute(AbstractMavenReport.java:98)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:417)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:554)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeStandaloneGoal(DefaultLifecycleExecutor.java:517)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:498)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:307)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:149)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:217)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:247)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:324)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
Caused by: org.apache.maven.reporting.MavenReportException: An error has occurred in javadoc report generation.
at org.apache.maven.plugin.javadoc.JavadocReport.executeReport(JavadocReport.java:841)
at org.apache.maven.plugin.javadoc.JavadocReport.generate(JavadocReport.java:583)
at org.apache.maven.reporting.AbstractMavenReport.execute(AbstractMavenReport.java:92)
... 16 more
Caused by: org.codehaus.plexus.util.cli.CommandLineException: Error while executing process.
at org.codehaus.plexus.util.cli.Commandline.execute(Commandline.java:679)
at org.codehaus.plexus.util.cli.CommandLineUtils.executeCommandLine(CommandLineUtils.java:69)
at org.codehaus.plexus.util.cli.CommandLineUtils.executeCommandLine(CommandLineUtils.java:56)
at org.apache.maven.plugin.javadoc.JavadocReport.executeReport(JavadocReport.java:831)
... 18 more
Caused by: java.io.IOException: /System/Library/Frameworks/JavaVM.framework/Versions/1.4.2/Home/../bin/javadoc: not found
at java.lang.UNIXProcess.forkAndExec(Native Method)
at java.lang.UNIXProcess.\<init>(UNIXProcess.java:54)
at java.lang.Runtime.execInternal(Native Method)
at java.lang.Runtime.exec(Runtime.java:566)
at org.codehaus.plexus.util.cli.Commandline.execute(Commandline.java:674)
... 21 more

the correct path should be $JAVA_HOME/bin/javadoc

not $JAVA_HOME/../bin/javadoc

at least that's on the mac.  not sure where java ends up on other platforms.

dave

---

**Attachments:**
- [MNG-1155-macosx-support-for-javadoc-plugin.diff](https://issues.apache.org/jira/secure/attachment/12716886/MNG-1155-macosx-support-for-javadoc-plugin.diff) (_953 bytes_)

**Comment by jira-importer** [comment]
**[Jerome Lacoste](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=lacostej)** commented

Should work on Max OS X. What about Mac OS?
