### ISSUE TITLE
[MJAVADOC-72] Aggregating javadocs doesn't work

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-javadoc-plugin#474]
**[syvalta](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=syvalta)** opened **[MJAVADOC-72](https://issues.apache.org/jira/browse/MJAVADOC-72?redirect=false)** and commented

When I define \<aggregate>true\</aggregate> to javadoc plugin configuration in parent pom, javadoc generation doesn't work from the parent (all other configuration options are default). If run under individual components, javadoc is generated without problems. It seems that the child dependencies aren't resolved:

Embedded error: Exit code: 1 - c:/code/apps/project/common/src/main/java/com/company/AbstractLogEnabled.java:3: package org.apache.log4j does not exist
import org.apache.log4j.Logger;

c:/code/apps/component/common-test/src/main/java/com/company/unittest/AbstractDatasourceEnabledTestCase.java:11: package org.apache.commons.dbcp does not exist
import org.apache.commons.dbcp.BasicDataSource;

And lot more similar errors.

Additionally, there are a huge number of ClassCastExceptions from javadoc.

java.lang.ClassCastException: com.sun.tools.javadoc.ClassDocImpl
at com.sun.tools.javadoc.AnnotationDescImpl.annotationType(AnnotationDescImpl.java:46)
at com.sun.tools.doclets.internal.toolkit.util.Util.isDeprecated(Util.java:804)
at com.sun.tools.doclets.formats.html.TagletWriterImpl.deprecatedTagOutput(TagletWriterImpl.java:85)
at com.sun.tools.doclets.internal.toolkit.taglets.DeprecatedTaglet.getTagletOutput(DeprecatedTaglet.java:40)
at com.sun.tools.doclets.formats.html.MethodWriterImpl.writeDeprecated(MethodWriterImpl.java:166)
at com.sun.tools.doclets.internal.toolkit.builders.MethodBuilder.buildDeprecationInfo(MethodBuilder.java:183)
at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at com.sun.tools.doclets.internal.toolkit.builders.MethodBuilder.invokeMethod(MethodBuilder.java:109)
at com.sun.tools.doclets.internal.toolkit.builders.AbstractBuilder.build(AbstractBuilder.java:90)
at com.sun.tools.doclets.internal.toolkit.builders.AbstractMemberBuilder.build(AbstractMemberBuilder.java:56)
at com.sun.tools.doclets.internal.toolkit.builders.MethodBuilder.buildMethodDoc(MethodBuilder.java:150)
at sun.reflect.GeneratedMethodAccessor36.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at com.sun.tools.doclets.internal.toolkit.builders.MethodBuilder.invokeMethod(MethodBuilder.java:109)
at com.sun.tools.doclets.internal.toolkit.builders.AbstractBuilder.build(AbstractBuilder.java:90)
at com.sun.tools.doclets.internal.toolkit.builders.AbstractMemberBuilder.build(AbstractMemberBuilder.java:56)
at com.sun.tools.doclets.internal.toolkit.builders.ClassBuilder.buildMethodDetails(ClassBuilder.java:322)
at sun.reflect.GeneratedMethodAccessor33.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at com.sun.tools.doclets.internal.toolkit.builders.ClassBuilder.invokeMethod(ClassBuilder.java:101)
at com.sun.tools.doclets.internal.toolkit.builders.AbstractBuilder.build(AbstractBuilder.java:90)
at com.sun.tools.doclets.internal.toolkit.builders.ClassBuilder.buildClassDoc(ClassBuilder.java:124)
at sun.reflect.GeneratedMethodAccessor7.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at com.sun.tools.doclets.internal.toolkit.builders.ClassBuilder.invokeMethod(ClassBuilder.java:101)
at com.sun.tools.doclets.internal.toolkit.builders.AbstractBuilder.build(AbstractBuilder.java:90)
at com.sun.tools.doclets.internal.toolkit.builders.ClassBuilder.build(ClassBuilder.java:108)
at com.sun.tools.doclets.formats.html.HtmlDoclet.generateClassFiles(HtmlDoclet.java:155)
at com.sun.tools.doclets.internal.toolkit.AbstractDoclet.generateClassFiles(AbstractDoclet.java:177)
at com.sun.tools.doclets.internal.toolkit.AbstractDoclet.generateClassFiles(AbstractDoclet.java:161)
at com.sun.tools.doclets.internal.toolkit.AbstractDoclet.startGeneration(AbstractDoclet.java:106)
at com.sun.tools.doclets.internal.toolkit.AbstractDoclet.start(AbstractDoclet.java:64)
at com.sun.tools.doclets.formats.html.HtmlDoclet.start(HtmlDoclet.java:42)
at com.sun.tools.doclets.standard.Standard.start(Standard.java:23)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at com.sun.tools.javadoc.DocletInvoker.invoke(DocletInvoker.java:269)
at com.sun.tools.javadoc.DocletInvoker.start(DocletInvoker.java:143)
at com.sun.tools.javadoc.Start.parseAndExecute(Start.java:340)
at com.sun.tools.javadoc.Start.begin(Start.java:128)
at com.sun.tools.javadoc.Main.execute(Main.java:41)
at com.sun.tools.javadoc.Main.main(Main.java:31)

---

**Affects:** 2.0

**Attachments:**
- [MJAVADOC-72.patch](https://issues.apache.org/jira/secure/attachment/12716995/MJAVADOC-72.patch) (_4.82 kB_)

7 votes, 7 watchers

**Comment by jira-importer** [comment]
**[Jochen Wiedmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jochen.wiedmann@gmail.com)** commented

This did not work for me too, initially. However, after I forced an upgrade to the 2.0-final version of the javadoc plugin (by specifiying a version in the reports section for this plugin) everything works fine. See the SVN version of the Apache XML-RPC package.

**Comment by jira-importer** [comment]
**[yogieric](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=yogieric)** commented

I'm experiencing this issue as well. I'm not sure how to upgrade to 2.0-final. I tried adding \<version>2.0-final\</version> inside \<plugin>\</plugin>, but it still fails. I get:
GroupId: org.apache.maven.plugins
ArtifactId: maven-javadoc-pluginVersion: 2.0-final
Reason: Unable to download the artifact from any repository
org.apache.maven.plugins:maven-javadoc-plugin:pom:2.0-final

Doesn't sound like the solution anyway.

**Comment by jira-importer** [comment]
**[Mathias Broekelmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mbroekelmann)** commented

This patch should fix the problem.

The problem was that the compile artifacts of the modules in the reactor where not initialized.

The solution in this patch is now to resolve the artifacts of each reactor project and add the compile artifacts to the classpath for javadoc generation. I've tested it with a large project structure (spring-rich) with multiple nested projects and it was working perfectly.

**Comment by jira-importer** [comment]
**[Rohnny Moland](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rohnny)** commented

I tried the patch from 20 august, and that seems to fix the problem. So I think this bug could be closed now.

**Comment by jira-importer** [comment]
**[Siveton Vincent](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=siveton)** commented

Applied with small changes (codestyle)
Bump to 1.0-beta-2-SNAPSHOT for maven-plugin-testing-harness to prevent test failures.

Thanks Mathias!
