### ISSUE TITLE
[MJAVADOC-127] Tests fail on MacOS X

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-javadoc-plugin#498]
**[Thomas Krammer](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=tkrammer)** opened **[MJAVADOC-127](https://issues.apache.org/jira/browse/MJAVADOC-127?redirect=false)** and commented

The build of the plugin fails on MacOS X with the following errors:

Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.182 sec <<< FAILURE!
Running org.apache.maven.plugin.javadoc.TagTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.311 sec

Results :

Tests in error:
testToFindJavadoc(org.apache.maven.plugin.javadoc.JavadocReportTest)
testJavadocResources(org.apache.maven.plugin.javadoc.JavadocReportTest)
testAggregateJavadocResources(org.apache.maven.plugin.javadoc.JavadocReportTest)
testDefaultConfig(org.apache.maven.plugin.javadoc.JavadocJarTest)
testInvalidDestdir(org.apache.maven.plugin.javadoc.JavadocJarTest)
testTestJavadoc(org.apache.maven.plugin.javadoc.TestJavadocReportTest)

The full output is attached.

This is the actual exception thrown by testGetQuotedPath (for some reason the exception isn't logged to stdout):

org.apache.maven.plugin.MojoExecutionException: An error has occurred in JavaDocs report generation:Exit code: 2 - /bin/bash: -c: line 1: unexpected EOF while looking for matching `''
/bin/bash: -c: line 2: syntax error: unexpected end of file

Command line was:"cd /Users/user/alienbrainWork/mvn/maven-javadoc-plugin/target/test/unit/quotedpath'test/target/site/apidocs && /System/Library/Frameworks/JavaVM.framework/Versions/1.5.0/Home/bin/javadoc" `@options` `@argfile`
at org.apache.maven.plugin.javadoc.JavadocReport.execute(JavadocReport.java:233)
at org.apache.maven.plugin.javadoc.JavadocReportTest.testQuotedPath(JavadocReportTest.java:508)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:585)
at junit.framework.TestCase.runTest(TestCase.java:154)
at junit.framework.TestCase.runBare(TestCase.java:127)
at junit.framework.TestResult$1.protect(TestResult.java:106)
at junit.framework.TestResult.runProtected(TestResult.java:124)
at junit.framework.TestResult.run(TestResult.java:109)
at junit.framework.TestCase.run(TestCase.java:118)
at junit.framework.TestSuite.runTest(TestSuite.java:208)
at junit.framework.TestSuite.run(TestSuite.java:203)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:585)
at org.apache.maven.surefire.junit.JUnitTestSet.execute(JUnitTestSet.java:213)
at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.executeTestSet(AbstractDirectoryTestSuite.java:138)
at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.execute(AbstractDirectoryTestSuite.java:125)
at org.apache.maven.surefire.Surefire.run(Surefire.java:132)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:585)
at org.apache.maven.surefire.booter.SurefireBooter.runSuitesInProcess(SurefireBooter.java:290)
at org.apache.maven.surefire.booter.SurefireBooter.main(SurefireBooter.java:818)
Caused by: org.apache.maven.reporting.MavenReportException: Exit code: 2 - /bin/bash: -c: line 1: unexpected EOF while looking for matching `''
/bin/bash: -c: line 2: syntax error: unexpected end of file

Command line was:"cd /Users/user/alienbrainWork/mvn/maven-javadoc-plugin/target/test/unit/quotedpath'test/target/site/apidocs && /System/Library/Frameworks/JavaVM.framework/Versions/1.5.0/Home/bin/javadoc" `@options` `@argfile`
at org.apache.maven.plugin.javadoc.AbstractJavadocMojo.executeReport(AbstractJavadocMojo.java:1404)
at org.apache.maven.plugin.javadoc.JavadocReport.generate(JavadocReport.java:131)
at org.apache.maven.plugin.javadoc.JavadocReport.execute(JavadocReport.java:219)
... 27 more

---

**Affects:** 2.3

**Attachments:**
- [ttt.txt](https://issues.apache.org/jira/secure/attachment/12717032/ttt.txt) (_39.51 kB_)

**Comment by jira-importer** [comment]
**[Siveton Vincent](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=siveton)** commented

depends on it for testQuotedPath()

**Comment by jira-importer** [comment]
**[Siveton Vincent](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=siveton)** commented

Fixed in svn
http://maven.zones.apache.org/continuum/buildResult.action?buildId=11342&projectId=23
