### ISSUE TITLE
[MJAVADOC-156] UnsupportedOperationException in multi module project

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-javadoc-plugin#514]
**[mork](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mork)** opened **[MJAVADOC-156](https://issues.apache.org/jira/browse/MJAVADOC-156?redirect=false)** and commented

Dealing with MJAVADOC-135, I switched on maven-javadoc-plugin version 2.4-SNAPSHOT
and I found the following problem:
when creating the javadoc report for site in a multimodule project (using a flat directory layout, so all three projects on the same
level), UnsupportedOperationException is thrown.
Say I have projA and projB each of them delcare maven-javadoc-plugin 2.4-SNAPSHOT as report dependency.
If I run mvn site on each project indipendently, the site (with javadoc report) works fine.
If I create a pom project which declares projA and projB as modules, running mvn site on there fails with the following exception:

java.lang.UnsupportedOperationException
at java.util.AbstractList.add(AbstractList.java:150)
at java.util.AbstractList.add(AbstractList.java:88)
at org.apache.maven.plugin.javadoc.AbstractJavadocMojo.addLinkofflineArguments(AbstractJavadocMojo.java:2461)
at org.apache.maven.plugin.javadoc.AbstractJavadocMojo.executeReport(AbstractJavadocMojo.java:1337)
at org.apache.maven.plugin.javadoc.JavadocReport.generate(JavadocReport.java:135)
at org.apache.maven.plugins.site.ReportDocumentRenderer.renderDocument(ReportDocumentRenderer.java:67)
at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.renderModule(DefaultSiteRenderer.java:239)
at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.render(DefaultSiteRenderer.java:115)
at org.apache.maven.plugins.site.SiteMojo.renderLocale(SiteMojo.java:124)
at org.apache.maven.plugins.site.SiteMojo.execute(SiteMojo.java:92)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:443)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:539)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:48
0)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:459)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.jav
a:311)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:278)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:143)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:334)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:125)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:280)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:324)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)

If i set the plugin dependency to maven-javadoc-plugin 2.3 the same goal runs fine.
This will become an issue for me as I am waiting for 2.4 to solve MJAVADOC-135
and I have a multimodule structure as the one described above.
I will post a sample project in a while.

---

**Attachments:**
- [MJAVADOC-156.zip](https://issues.apache.org/jira/secure/attachment/12716870/MJAVADOC-156.zip) (_4.08 kB_)

**Comment by jira-importer** [comment]
**[mork](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mork)** commented

sample multimodule projects

**Comment by jira-importer** [comment]
**[mork](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mork)** commented

forgot to specify affected version: 2.4 (using snapshot maven-javadoc-plugin-2.4-20071011.225201-1)

**Comment by jira-importer** [comment]
**[Siveton Vincent](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=siveton)** commented

fixed in r586448
