### ISSUE TITLE
[MJAVADOC-101] Embedded error: Error rendering Maven report

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-javadoc-plugin#517]
**[Bose Daggubati](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bose_100)** opened **[MJAVADOC-101](https://issues.apache.org/jira/browse/MJAVADOC-101?redirect=false)** and commented

2 errors
1 warning
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Error during page generation

Embedded error: Error rendering Maven report: Exit code: 1 - C:/ExpressContact/StandAlone/RandomizationEngine/src/main/java/com/express_scripts/imms/randeng/domain/Client.java:21: warning: as of release 1.4, assert
is a keyword, and may not be used as an identifier
assert (planTypeId == null) || (bplId == null) : "A Client (from a Randomization Standpoint) should not have both a PLAN TYPE ID and BPL ID";
^
C:/ExpressContact/StandAlone/RandomizationEngine/src/main/java/com/express_scripts/imms/randeng/domain/Client.java:21: not a statement
assert (planTypeId == null) || (bplId == null) : "A Client (from a Randomization Standpoint) should not have both a PLAN TYPE ID and BPL ID";
^
C:/ExpressContact/StandAlone/RandomizationEngine/src/main/java/com/express_scripts/imms/randeng/domain/Client.java:21: ';' expected
assert (planTypeId == null) || (bplId == null) : "A Client (from a Randomization Standpoint) should not have both a PLAN TYPE ID and BPL ID";
^

[INFO] ------------------------------------------------------------------------
[DEBUG] Trace
org.apache.maven.lifecycle.LifecycleExecutionException: Error during page generation
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:559)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:475)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:454)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:306)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:273)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:140)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:322)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:115)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:256)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:324)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
Caused by: org.apache.maven.plugin.MojoExecutionException: Error during page generation
at org.apache.maven.plugins.site.SiteMojo.execute(SiteMojo.java:97)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:412)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:534)
... 16 more
Caused by: org.apache.maven.doxia.siterenderer.RendererException: Error rendering Maven report: Exit code: 1 - C:/ExpressContact/StandAlone/RandomizationEngine/src/main/java/com/express_scripts/imms/randeng/domain/C
lient.java:21: warning: as of release 1.4, assert is a keyword, and may not be used as an identifier
assert (planTypeId == null) || (bplId == null) : "A Client (from a Randomization Standpoint) should not have both a PLAN TYPE ID and BPL ID";
^
C:/ExpressContact/StandAlone/RandomizationEngine/src/main/java/com/express_scripts/imms/randeng/domain/Client.java:21: not a statement
assert (planTypeId == null) || (bplId == null) : "A Client (from a Randomization Standpoint) should not have both a PLAN TYPE ID and BPL ID";
^
C:/ExpressContact/StandAlone/RandomizationEngine/src/main/java/com/express_scripts/imms/randeng/domain/Client.java:21: ';' expected
assert (planTypeId == null) || (bplId == null) : "A Client (from a Randomization Standpoint) should not have both a PLAN TYPE ID and BPL ID";
^

    at org.apache.maven.plugins.site.ReportDocumentRenderer.renderDocument(ReportDocumentRenderer.java:71)
    at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.renderModule(DefaultSiteRenderer.java:239)
    at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.render(DefaultSiteRenderer.java:115)
    at org.apache.maven.plugins.site.SiteMojo.renderLocale(SiteMojo.java:124)
    at org.apache.maven.plugins.site.SiteMojo.execute(SiteMojo.java:92)
    ... 18 more

Caused by: org.apache.maven.reporting.MavenReportException: Exit code: 1 - C:/ExpressContact/StandAlone/RandomizationEngine/src/main/java/com/express_scripts/imms/randeng/domain/Client.java:21: warning: as of releas
e 1.4, assert is a keyword, and may not be used as an identifier
assert (planTypeId == null) || (bplId == null) : "A Client (from a Randomization Standpoint) should not have both a PLAN TYPE ID and BPL ID";
^
C:/ExpressContact/StandAlone/RandomizationEngine/src/main/java/com/express_scripts/imms/randeng/domain/Client.java:21: not a statement
assert (planTypeId == null) || (bplId == null) : "A Client (from a Randomization Standpoint) should not have both a PLAN TYPE ID and BPL ID";
^
C:/ExpressContact/StandAlone/RandomizationEngine/src/main/java/com/express_scripts/imms/randeng/domain/Client.java:21: ';' expected
assert (planTypeId == null) || (bplId == null) : "A Client (from a Randomization Standpoint) should not have both a PLAN TYPE ID and BPL ID";
^

    at org.apache.maven.plugin.javadoc.AbstractJavadocMojo.executeReport(AbstractJavadocMojo.java:845)
    at org.apache.maven.plugin.javadoc.JavadocReport.generate(JavadocReport.java:104)
    at org.apache.maven.plugins.site.ReportDocumentRenderer.renderDocument(ReportDocumentRenderer.java:67)
    ... 22 more

[INFO] ------------------------------------------------------------------------
[INFO] Total time: 37 seconds
[INFO] Finished at: Tue Nov 14 13:31:30 CST 2006
[INFO] Final Memory: 28M/50M
[INFO] --------------------------------------------------------------------

---

**Attachments:**
- [javadoc-2.1.log](https://issues.apache.org/jira/secure/attachment/12716997/javadoc-2.1.log) (_41.09 kB_)
- [Maven Site issue.txt](https://issues.apache.org/jira/secure/attachment/12717053/Maven+Site+issue.txt) (_213.92 kB_)
- [pom.xml](https://issues.apache.org/jira/secure/attachment/12716865/pom.xml) (_3.75 kB_)
- [pom.xml](https://issues.apache.org/jira/secure/attachment/12716888/pom.xml) (_4.46 kB_)

2 votes, 3 watchers

**Comment by jira-importer** [comment]
**[Bose Daggubati](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bose_100)** commented

You may please fwd this to javadoc team.

How can i run this site command excluding this javadoc generation

**Comment by jira-importer** [comment]
**[Siveton Vincent](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=siveton)** commented

You used the maven-javadoc-plugin version 2.0. Could you try with maven-javadoc-plugin:2.1 ?
The option -U doesnt update plugins in reporting section so you need to call:
mvn -U javadoc:javadoc

Waiting for your comments.

**Comment by jira-importer** [comment]
**[Samuel Langlois](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=langlois)** commented

I have the same error with maven-javadoc-plugin version 2.1
I attach the result of "mvn javadoc:javadoc -X"
Is there any workaround?

Thanks

**Comment by jira-importer** [comment]
**[Samuel Langlois](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=langlois)** commented

More info on this subject...

Actually, I'm not sure this issue belongs to the javadoc plugin.
I added a \<excludePackageNames> in the maven-javadoc-plugin configuration to exclude the code containing the assert() method,
and I am now able to run "mvn javadoc:javadoc" without error.

However, "mvn site:site" still fails with the following trace:

[INFO] ------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Error during page generation

Embedded error: Error rendering Maven report: Exit code: 1 - /nfs/bizrules/jrules/users/langlois/mavenpoc/engine/engine/jrules-engine-context/src/main/java/ilog/rules/engine/IlrContext.java:1199: as of release 1.4, assert is a keyword, and may not be used as an identifier
public synchronized void assert(Object object) {
^

[INFO] ------------------------------------------------------------------------
[DEBUG] Trace
org.apache.maven.lifecycle.LifecycleExecutionException: Error during page generation
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:559)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeStandaloneGoal(DefaultLifecycleExecutor.java:488)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:458)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:306)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:273)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:140)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:327)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:120)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:263)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:324)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
Caused by: org.apache.maven.plugin.MojoExecutionException: Error during page generation
at org.apache.maven.plugins.site.SiteMojo.execute(SiteMojo.java:97)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:417)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:534)
... 16 more
Caused by: org.apache.maven.doxia.siterenderer.RendererException: Error rendering Maven report: Exit code: 1 - /nfs/bizrules/jrules/users/langlois/mavenpoc/engine/engine/jrules-engine-context/src/main/java/ilog/rules/engine/IlrContext.java:1199: as of release 1.4, assert is a keyword, and may not be used as an identifier
public synchronized void assert(Object object) {
^

    at org.apache.maven.plugins.site.ReportDocumentRenderer.renderDocument(ReportDocumentRenderer.java:71)
    at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.renderModule(DefaultSiteRenderer.java:239)
    at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.render(DefaultSiteRenderer.java:115)
    at org.apache.maven.plugins.site.SiteMojo.renderLocale(SiteMojo.java:124)
    at org.apache.maven.plugins.site.SiteMojo.execute(SiteMojo.java:92)
    ... 18 more

Caused by: org.apache.maven.reporting.MavenReportException: Exit code: 1 - /nfs/bizrules/jrules/users/langlois/mavenpoc/engine/engine/jrules-engine-context/src/main/java/ilog/rules/engine/IlrContext.java:1199: as of release 1.4, assert is a keyword, and may not be used as an identifier
public synchronized void assert(Object object) {
^

    at org.apache.maven.plugin.javadoc.AbstractJavadocMojo.executeReport(AbstractJavadocMojo.java:845)
    at org.apache.maven.plugin.javadoc.JavadocReport.generate(JavadocReport.java:104)
    at org.apache.maven.plugins.site.ReportDocumentRenderer.renderDocument(ReportDocumentRenderer.java:67)
    ... 22 more

Is there any way out?
(We unfortunately cannot remove this stupid assert() method for compatibility reasons.)

**Comment by jira-importer** [comment]
**[Trustin Lee](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=trustin)** commented

I found this issue goes away if I run 'mvn compile' before running 'mvn site'.

**Comment by jira-importer** [comment]
**[Siveton Vincent](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=siveton)** commented

Adding " -Dsource=1.4" should resolve this error.
http://java.sun.com/j2se/1.4.2/docs/tooldocs/windows/javadoc.html#source
