### ISSUE TITLE
[MJAVADOC-107] unknown error: "invalid header field"

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-javadoc-plugin#526]
**[Jörg Hohwiller](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=joerg.hohwiller@sdm.de)** opened **[MJAVADOC-107](https://issues.apache.org/jira/browse/MJAVADOC-107?redirect=false)** and commented

When I create the javadoc of one of my modules, I get the error blow - but I do not have a clue whats wrong.
I tried a clean and rebuild but nothing changed. Exception messages from maven do not seem to enlighten me.
What header field? A header field of the prompted jar file?

Caused by: org.apache.maven.reporting.MavenReportException: Exit code: 1 - error: error reading C:\WINDOWS\Profiles\hohwille\.m2\repository\net\sf\mmm\mmm-uit-swt\0.9.0-SNAPSHOT\mmm-uit-swt-0.9.0-SNAPSHOT.jar; invalid header field
at org.apache.maven.plugin.javadoc.AbstractJavadocMojo.executeReport(AbstractJavadocMojo.java:845)
at org.apache.maven.plugin.javadoc.JavadocReport.generate(JavadocReport.java:104)
at org.apache.maven.plugin.javadoc.JavadocReport.execute(JavadocReport.java:166)
... 18 more

---

**Affects:** 2.0

**Comment by jira-importer** [comment]
**[Carlos Sanchez Gonzalez](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=carlos)** commented

Your file C:\WINDOWS\Profiles\hohwille\.m2\repository\net\sf\mmm\mmm-uit-swt\0.9.0-SNAPSHOT\mmm-uit-swt-0.9.0-SNAPSHOT.jar is probably corrupt or has an incorrect manifest

**Comment by jira-importer** [comment]
**[Mathew Crocker](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mcrocker)** commented

I had a similar problem that was related to the existence of carriage returns and tab characters in the \<description> element in the pom.xml file.  The content of this element gets copied by the jar plugin to the Specification-Title: field in the MANIFEST.MF with some strange wrapping.  Putting the entire contents of the \<description> element on a single line seems to solve the problem.

This work-around should not be required. The Maven XML parser should "do the right thing" with whitespace and not include the leading tabs in the description entry.

Using the encoding element in the configurations section of the resources plugin, as suggested by on posting, did not help.

**Comment by jira-importer** [comment]
**[Carlos Sanchez Gonzalez](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=carlos)** commented

you need to upgrade the maven compiler and jar plugins, that issue should have been fixed
