### ISSUE TITLE
[MJAVADOC-254] aggregation fails to get classpath, blows up

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-javadoc-plugin#561]
**[Benson Margulies](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bmargulies)** opened **[MJAVADOC-254](https://issues.apache.org/jira/browse/MJAVADOC-254?redirect=false)** and commented

javadoc:aggregate blows up with an error inside of the javadoc tool. The immediate problem is that junit isn't in the classpath, so junit annotations explode. If I add junit to the dependencies of the aggregating project, I just run into trouble with other missing annotations, like some for Spring.

[DEBUG] /System/Library/Frameworks/JavaVM.framework/Versions/1.5.0/Home/bin/javadoc `@options` `@packages`
1 error
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] An error has occurred in JavaDocs report generation:Exit code: 1 - javadoc: error - In doclet class com.sun.tools.doclets.standard.Standard,  method start has thrown an exception java.lang.reflect.InvocationTargetException
java.lang.AssertionError: cannot find method org.junit.runner.RunWith.value()
at com.sun.tools.javac.jvm.ClassReader$AnnotationDeproxy.findAccessMethod(ClassReader.java:1074)
at com.sun.tools.javac.jvm.ClassReader$AnnotationDeproxy.deproxyCompound(ClassReader.java:1057)
at com.sun.tools.javac.jvm.ClassReader$AnnotationDeproxy.deproxyCompoundList(ClassReader.java:1046)
at com.sun.tools.javac.jvm.ClassReader$AnnotationCompleter.enterAnnotation(ClassReader.java:1195)
at com.sun.tools.javac.comp.Annotate.flush(Annotate.java:94)
at com.sun.tools.javac.jvm.ClassReader.complete(ClassReader.java:1541)
at com.sun.tools.javac.code.Symbol.complete(Symbol.java:355)
at com.sun.tools.javac.code.Symbol$ClassSymbol.complete(Symbol.java:612)
at com.sun.tools.javac.code.Symbol$ClassSymbol.flags(Symbol.java:550)
at com.sun.tools.javadoc.ClassDocImpl.getFlags(ClassDocImpl.java:105)
at com.sun.tools.javadoc.ClassDocImpl.isAnnotationType(ClassDocImpl.java:116)
at com.sun.tools.javadoc.DocEnv.isAnnotationType(DocEnv.java:574)
at com.sun.tools.javadoc.DocEnv.getClassDoc(DocEnv.java:546)
at com.sun.tools.javadoc.PackageDocImpl.getClasses(PackageDocImpl.java:152)
at com.sun.tools.javadoc.PackageDocImpl.addAllClassesTo(PackageDocImpl.java:168)
at com.sun.tools.javadoc.RootDocImpl.classes(RootDocImpl.java:178)
at com.sun.tools.doclets.internal.toolkit.AbstractDoclet.startGeneration(AbstractDoclet.java:96)
at com.sun.tools.doclets.internal.toolkit.AbstractDoclet.start(AbstractDoclet.java:64)
at com.sun.tools.doclets.formats.html.HtmlDoclet.start(HtmlDoclet.java:42)
at com.sun.tools.doclets.standard.Standard.start(Standard.java:23)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:585)
at com.sun.tools.javadoc.DocletInvoker.invoke(DocletInvoker.java:269)
at com.sun.tools.javadoc.DocletInvoker.start(DocletInvoker.java:143)
at com.sun.tools.javadoc.Start.parseAndExecute(Start.java:340)
at com.sun.tools.javadoc.Start.begin(Start.java:128)
at com.sun.tools.javadoc.Main.execute(Main.java:41)
at com.sun.tools.javadoc.Main.main(Main.java:31)

Command line was:/System/Library/Frameworks/JavaVM.framework/Versions/1.5.0/Home/bin/javadoc `@options` `@packages`

---

**Affects:** 2.6

**Attachments:**
- [foo](https://issues.apache.org/jira/secure/attachment/12716898/foo) (_213.73 kB_)
- [javadoc.sh](https://issues.apache.org/jira/secure/attachment/12717036/javadoc.sh) (_94 bytes_)
- [options](https://issues.apache.org/jira/secure/attachment/12716964/options) (_4.80 kB_)
- [packages](https://issues.apache.org/jira/secure/attachment/12716940/packages) (_647 bytes_)

**Comment by jira-importer** [comment]
**[Benson Margulies](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bmargulies)** commented

Sadly, not easily. I have two pretty big multi-module projects. One works, one does not.

Did the log I posted give you any clues?

I could try to boil down if not.

**Comment by jira-importer** [comment]
**[Siveton Vincent](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=siveton)** commented

Not really, but you send us the javadoc files using -Ddebug [1]

[1] http://maven.apache.org/plugins/maven-javadoc-plugin/faq.html#How_to_know_exactly_the_Javadoc_command_line

**Comment by jira-importer** [comment]
**[Benson Margulies](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bmargulies)** commented

javadoc.sh

**Comment by jira-importer** [comment]
**[Benson Margulies](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bmargulies)** commented

And the details.

**Comment by jira-importer** [comment]
**[Benson Margulies](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bmargulies)** commented

There was no 'files' file left behind.

**Comment by jira-importer** [comment]
**[Benson Margulies](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bmargulies)** commented

So, where is the list of source directories hiding?

**Comment by jira-importer** [comment]
**[Benson Margulies](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bmargulies)** commented

OK, here's the situation.

If module a exports its test with a classifier of 'tests', and module b depends on it without a scope, then this happens. Not too surprisingly, the classified jar doesn't carry along its dependencies.

I think you want to close this out as pilot error.

**Comment by jira-importer** [comment]
**[Siveton Vincent](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=siveton)** commented

as requested by Benson
