### ISSUE TITLE
[MJAVADOC-297] NullPointerException in AbstractFixJavadocMojo.writeParamTag()

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-javadoc-plugin#594]
**[Graham Leggett](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=minfrin)** opened **[MJAVADOC-297](https://issues.apache.org/jira/browse/MJAVADOC-297?redirect=false)** and commented

While attempting to run the javadoc:fix goal against source code, v2.7 of the javadoc plugin crashed as follows:

```
[INFO] ------------------------------------------------------------------------
[ERROR] FATAL ERROR
[INFO] ------------------------------------------------------------------------
[INFO] null
[INFO] ------------------------------------------------------------------------
[INFO] Trace
java.lang.NullPointerException
	at org.apache.maven.plugin.javadoc.AbstractFixJavadocMojo.writeParamTag(AbstractFixJavadocMojo.java:1958)
	at org.apache.maven.plugin.javadoc.AbstractFixJavadocMojo.updateJavadocTags(AbstractFixJavadocMojo.java:1842)
	at org.apache.maven.plugin.javadoc.AbstractFixJavadocMojo.updateJavadocTags(AbstractFixJavadocMojo.java:1747)
	at org.apache.maven.plugin.javadoc.AbstractFixJavadocMojo.updateJavadocComment(AbstractFixJavadocMojo.java:1658)
	at org.apache.maven.plugin.javadoc.AbstractFixJavadocMojo.updateEntityComment(AbstractFixJavadocMojo.java:1527)
	at org.apache.maven.plugin.javadoc.AbstractFixJavadocMojo.fixMethodComment(AbstractFixJavadocMojo.java:1391)
	at org.apache.maven.plugin.javadoc.AbstractFixJavadocMojo.processFix(AbstractFixJavadocMojo.java:993)
	at org.apache.maven.plugin.javadoc.AbstractFixJavadocMojo.execute(AbstractFixJavadocMojo.java:405)
	at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:483)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:678)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeStandaloneGoal(DefaultLifecycleExecutor.java:553)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:523)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:371)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:332)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:181)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:356)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:137)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:362)
	at org.apache.maven.cli.compat.CompatibleMain.main(CompatibleMain.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
	at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
	at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
```

---

**Affects:** 2.7

**Comment by jira-importer** [comment]
**[Siveton Vincent](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=siveton)** commented

It seems that a given javadoc param has no type. Could you isolate your error and give us a sample?

**Comment by jira-importer** [comment]
**[Hervé Boutemy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=hboutemy)** commented

Could you isolate your error and give us a sample?

**Comment by jira-importer** [comment]
**[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte)** commented

Extracted this ocde fragment from the tagged class.

```
private void writeParamTag( final StringBuffer sb, final JavaMethod javaMethod,
                                final JavaEntityTags javaEntityTags, String[] params )
    {
        params = fixQdox173( params );

        String paramName = params[0];

        if ( !fixTag( PARAM_TAG ) )
        {
            // write original param tag if found
            String originalJavadocTag = javaEntityTags.getJavadocParamTag( paramName );
            if ( originalJavadocTag != null )
            {
                sb.append( originalJavadocTag );
            }
            return;
        }

        boolean found = false;
        JavaParameter javaParam = javaMethod.getParameterByName( paramName );
        if ( javaParam == null )
        {
            // is generic?
            TypeVariable[] typeParams = javaMethod.getTypeParameters();
            for ( int i = 0; i < typeParams.length; i++ )
            {
                if ( typeParams[i].getGenericValue().equals( paramName ) )
                {
                    found = true;
                }
            }
        }
        else
        {
            found = true;
        }

        if ( !found )
        {
            if ( getLog().isWarnEnabled() )
            {
                StringBuffer warn = new StringBuffer();

                warn.append( "Fixed unknown param '" ).append( paramName ).append( "' defined in " );
                warn.append( getJavaMethodAsString( javaMethod ) );

                getLog().warn( warn.toString() );
            }

            if ( sb.toString().endsWith( EOL ) )
            {
                sb.delete( sb.toString().lastIndexOf( EOL ), sb.toString().length() );
            }
        }
        else
        {
            String originalJavadocTag = javaEntityTags.getJavadocParamTag( paramName );
            if ( originalJavadocTag != null )
            {
                sb.append( originalJavadocTag );
                String s = "@" + PARAM_TAG + " " + paramName;
                if ( StringUtils.removeDuplicateWhitespace( originalJavadocTag ).trim().endsWith( s ) )
                {
                    sb.append( " " );
                    sb.append( getDefaultJavadocForType( javaParam.getType() ) );
                }
            }
        }
    }
```

The NPE is caused in one of the final lines: `sb.append( getDefaultJavadocForType( javaParam.getType() ) );`
`sb` can't be `null` since it's already used, so it has to be `javaParam`.
Two options I can think of: `@param` is empty or it has an invalid name.
Shouldn't be too hard to find out.

**Comment by jira-importer** [comment]
**[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte)** commented

I can't figure out how it is possible that a NPE is thrown here.
Since there's no testcase it is very hard to trace back the cause.
Closing it as 'incomplete'
