### ISSUE TITLE
[MJAVADOC-342] An incomplete fix for the NPE bugs in AbstractJavadocMojo.java

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-javadoc-plugin#641]
**[Guangtai Liang](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=guangtai)** opened **[MJAVADOC-342](https://issues.apache.org/jira/browse/MJAVADOC-342?redirect=false)** and commented

The fix revision 554202 was aimed to remove an NPE bug on the  returned value of  "getJavadocDirectory()" in the method "getSourcePaths " of the file "/maven/plugins/trunk/maven-javadoc-plugin/src/main/java/org/apache/maven/plugin/javadoc/AbstractJavadocMojo.java" , but it is incomplete.
Since the returned value  "getJavadocDirectory()" could be null during the runtime execution, its value should also be null-checked before being dereferenced in other methods.

The buggy code locations the same fix needs to be applied at are as bellows:

Line 2401 of the method "copyJavadocResources";
Line 1505 of the method "getSourcePaths".

---

1 votes, 2 watchers

**Comment by jira-importer** [comment]
**[Marcin Domanski](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=adie)** commented

This is true p.i.t.a. Out of 3 projects on javadoc:fix (v2.8.1)
* 1 failed with NPE on:
  * ```
  java.lang.NullPointerException
  at org.apache.maven.plugin.javadoc.AbstractFixJavadocMojo.writeParamTag(AbstractFixJavadocMojo.java:1994)

```
* the other failed with (seems to be fixed in Qdox already):
** ```
java.lang.ArrayIndexOutOfBoundsException: 500
        at com.thoughtworks.qdox.parser.impl.Parser.val_push(Parser.java:142)
        at com.thoughtworks.qdox.parser.impl.Parser.yyparse(Parser.java:1303)
        at com.thoughtworks.qdox.parser.impl.Parser.parse(Parser.java:999)
        at com.thoughtworks.qdox.JavaDocBuilder.addSource(JavaDocBuilder.java:353)
        at com.thoughtworks.qdox.JavaDocBuilder.addSource(JavaDocBuilder.java:381)
        at com.thoughtworks.qdox.JavaDocBuilder.addSource(JavaDocBuilder.java:377)
        at org.apache.maven.plugin.javadoc.AbstractFixJavadocMojo.getQdoxClasses(AbstractFixJavadocMojo.java:855)
```

* last one was successful

**Comment by jira-importer** [comment]
**[Benson Margulies](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bmargulies)** commented

THis is more likely to get fixed with test case(s) attached.

**Comment by jira-importer** [comment]
**[Benson Margulies](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bmargulies)** commented

---

r1385200 | bimargulies | 2012-09-15 19:22:45 -0400 (Sat, 15 Sep 2012) | 4 lines

MJAVADOC-342: An incomplete fix for the NPE bugs in AbstractJavadocMojo.java
o protect all the calls to getJavadocDirectory
o update to threadsafe version of maven-shade-plugin.
