### ISSUE TITLE
[MJAVADOC-409] Generating Javadoc no longer works with 2.10

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-javadoc-plugin#704]
**[Wim Deblauwe](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=wim.deblauwe@gmail.com)** opened **[MJAVADOC-409](https://issues.apache.org/jira/browse/MJAVADOC-409?redirect=false)** and commented

If I run javadoc using 2.9, then javadoc is generated without issue:

`mvn org.apache.maven.plugins:maven-javadoc-plugin:2.9:javadoc`

However, using version 2.10, the build fails:

`mvn org.apache.maven.plugins:maven-javadoc-plugin:2.10:javadoc`

There is a very big stack trace. One of the things that is shown is this:

```
[ERROR] java.lang.ClassCastException: com.sun.tools.javadoc.ClassDocImpl cannot be cast to com.sun.javadoc.AnnotationTypeDoc
[ERROR] at com.sun.tools.javadoc.AnnotationDescImpl.annotationType(AnnotationDescImpl.java:46)
[ERROR] at com.sun.tools.doclets.internal.toolkit.util.ClassUseMapper.mapAnnotations(ClassUseMapper.java:439)
[ERROR] at com.sun.tools.doclets.internal.toolkit.util.ClassUseMapper.mapExecutable(ClassUseMapper.java:297)
[ERROR] at com.sun.tools.doclets.internal.toolkit.util.ClassUseMapper.<init>(ClassUseMapper.java:196)
[ERROR] at com.sun.tools.doclets.formats.html.ClassUseWriter.generate(ClassUseWriter.java:109)
[ERROR] at com.sun.tools.doclets.formats.html.HtmlDoclet.generateOtherFiles(HtmlDoclet.java:92)
[ERROR] at com.sun.tools.doclets.internal.toolkit.AbstractDoclet.startGeneration(AbstractDoclet.java:122)
[ERROR] at com.sun.tools.doclets.internal.toolkit.AbstractDoclet.start(AbstractDoclet.java:64)
[ERROR] at com.sun.tools.doclets.formats.html.HtmlDoclet.start(HtmlDoclet.java:42)
[ERROR] at com.sun.tools.doclets.standard.Standard.start(Standard.java:23)
[ERROR] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
[ERROR] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
[ERROR] at java.lang.reflect.Method.invoke(Method.java:597)
[ERROR] at com.sun.tools.javadoc.DocletInvoker.invoke(DocletInvoker.java:269)
[ERROR] at com.sun.tools.javadoc.DocletInvoker.start(DocletInvoker.java:143)
[ERROR] at com.sun.tools.javadoc.Start.parseAndExecute(Start.java:340)
[ERROR] at com.sun.tools.javadoc.Start.begin(Start.java:128)
[ERROR] at com.sun.tools.javadoc.Main.execute(Main.java:41)
[ERROR] at com.sun.tools.javadoc.Main.main(Main.java:31)
[ERROR]
[ERROR] Command line was: /Library/Java/JavaVirtualMachines/1.6.0_65-b14-462.jdk/Contents/Home/bin/javadoc @options @packages @argfile
[ERROR]
```

---

**Affects:** 2.10

**Issue Links:**
- [MJAVADOC-407](https://issues.apache.org/jira/browse/MJAVADOC-407) Cannot parse annotations when generating javadoc
 (_**"duplicates"**_)

2 votes, 3 watchers

**Comment by jira-importer** [comment]
**[Chris Gamache](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cgamache)** commented

I have the same issue. FWIW, the problem is the same using Maven 3.0.5 and Maven 3.2.2.

**Comment by jira-importer** [comment]
**[Ida de Groot](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=idadegroot)** commented

Same issue using:

```
mvn -version
Apache Maven 3.1.0 (893ca28a1da9d5f51ac03827af98bb730128f9f2; 2013-06-28 04:15:32+0200)
Maven home: D:\maven\apache-maven-3.1.0
Java version: 1.7.0_21, vendor: Oracle Corporation
Java home: C:\Progra~1\Java\jdk1.7.0_21\jre
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 7", version: "6.1", arch: "amd64", family: "windows"
```

mvn release:perform would not work until we found out we did not manage the version of the javadoc plugin.

Adding javadoc plugin with version 2.9.1 to the pluginManagement section made the release:perform work again:

```
<plugin>
  <groupId>org.apache.maven.plugins</groupId>
  <artifactId>maven-javadoc-plugin</artifactId>
  <version>2.9.1</version>
</plugin>
```
