### ISSUE TITLE
[MJAVADOC-485] Upgrade to commons-lang3

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-javadoc-plugin#783]
**[Philippe Marschall](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=marschall)** opened **[MJAVADOC-485](https://issues.apache.org/jira/browse/MJAVADOC-485?redirect=false)** and commented

The plugin is currently on commons-lang 2.6, the most recent version is 3.6.

[The upgrade](https://commons.apache.org/proper/commons-lang/article3_0.html) is fairly trivial expect one point, `SystemUtils.JAVA_VERSION_FLOAT` is no longer available. For some parts there are easy fixes but for `AbstractJavadocMojo` the simplest fix seemed to use `JavadocUtil#parseJavadocVersion(String)`.

---

**Affects:** 2.10.4

**Issue Links:**
- [MJAVADOC-488](https://issues.apache.org/jira/browse/MJAVADOC-488) Latest jdk9 version causes StringIndexOutOfBoundsException
 (_**"is duplicated by"**_)
- [FLINK-15633](https://issues.apache.org/jira/browse/FLINK-15633) Javadocs cannot be built on Java 11

**Remote Links:**
- [GitHub Pull Request #119
](https://github.com/apache/maven-plugins/pull/119)

2 votes, 6 watchers

**Comment by jira-importer** [comment]
**[Mandrikov Evgeny Andreevich](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=godin)** commented

This seems to be useful for Java 9 - while plugin version 2.10.4 works with b171, it fails with b175 as following:

```
Apache Maven 3.5.0 (ff8f5e7444045639af65f6095c62210b5713f426; 2017-04-03T21:39:06+02:00)
Maven home: /home/godin/applications/apache-maven-3.5.0
Java version: 9, vendor: Oracle Corporation
Java home: /home/godin/.java-select/versions/jdk-9+175_linux-x64_bin
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.1.15-gentoo-r1", arch: "amd64", family: "unix"
...
[WARNING] Error injecting: org.apache.maven.plugin.javadoc.JavadocJar
java.lang.ExceptionInInitializerError
        at org.apache.maven.plugin.javadoc.AbstractJavadocMojo.<clinit>(AbstractJavadocMojo.java:195)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
        at com.google.inject.internal.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:86)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:105)
        at com.google.inject.internal.ConstructorInjector.access$000(ConstructorInjector.java:32)
        at com.google.inject.internal.ConstructorInjector$1.call(ConstructorInjector.java:89)
        at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:115)
        at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:133)
        at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:68)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:87)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:267)
        at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1016)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1103)
        at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1012)
        at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1051)
        at org.eclipse.sisu.space.AbstractDeferredClass.get(AbstractDeferredClass.java:48)
        at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:81)
Caused by: java.lang.StringIndexOutOfBoundsException: begin 0, end 3, length 1
        at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3116)
        at java.base/java.lang.String.substring(String.java:1885)
        at org.apache.commons.lang.SystemUtils.getJavaVersionAsFloat(SystemUtils.java:1133)
        at org.apache.commons.lang.SystemUtils.<clinit>(SystemUtils.java:818)
        at org.apache.maven.plugin.javadoc.AbstractJavadocMojo.<clinit>(AbstractJavadocMojo.java:195)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
        at com.google.inject.internal.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:86)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:105)
        at com.google.inject.internal.ConstructorInjector.access$000(ConstructorInjector.java:32)
        at com.google.inject.internal.ConstructorInjector$1.call(ConstructorInjector.java:89)
        at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:115)
        at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:133)
        at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:68)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:87)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:267)
        at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1016)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1103)
```

```
java version "9"
Java(TM) SE Runtime Environment (build 9+175)
Java HotSpot(TM) 64-Bit Server VM (build 9+175, mixed mode)
```

**Comment by jira-importer** [comment]
**[Peter Ansell](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=p_ansell)** commented

I can't reproduce the MJAVADOC-488 issue using the 3.0.0-SNAPSHOT in trunk (but I can replicate it using 2.10.4, which is why I am here). This is despite the commons-lang:2.6 version still being present in the pom.xml file, so it may not be a complete duplicate of this issue, as the "9" versus "9-ea" runtime failure seems to be fixed already.

There is still a warning about illegal reflective access by commons-lang, which was downgraded by default from failure in previous 9-ea releases to just a warning in 9b175 to give people time to fix their code:

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.commons.lang.builder.EqualsBuilder (file:/home/mint/.m2/repository/commons-lang/commons-lang/2.6/commons-lang-2.6.jar) to field java.util.ArrayList.serialVersionUID
WARNING: Please consider reporting this to the maintainers of org.apache.commons.lang.builder.EqualsBuilder
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

There are still test failures when building the trunk maven-javadoc-plugin with JDK-9. However, running javadoc:javadoc on a Java-9 built project after using JDK-9b175 to build maven-javadoc-plugin with "-DskipTests" seems to be still creating useful javadoc HTML pages so the test failures aren't signals that it is completely broken:

```

Results :

Failed tests: 
  org.apache.maven.plugin.javadoc.JavadocReportTest#testDocfiles AssertionFailedError
  org.apache.maven.plugin.javadoc.JavadocReportTest#testJavadocResources AssertionFailedError
  org.apache.maven.plugin.javadoc.JavadocReportTest#testTagletArtifacts AssertionFailedError
Tests in error: 
  org.apache.maven.plugin.javadoc.FixJavadocMojoTest#testFix MavenInvocationException
  org.apache.maven.plugin.javadoc.FixJavadocMojoTest#testFixJdk5 MavenInvocationException
  org.apache.maven.plugin.javadoc.FixJavadocMojoTest#testFixJdk6 MavenInvocationException
  org.apache.maven.plugin.javadoc.JavadocReportTest#testJdk5 MojoExecutionException

Tests run: 59, Failures: 3, Errors: 4, Skipped: 0
```

**Comment by jira-importer** [comment]
**[Mandrikov Evgeny Andreevich](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=godin)** commented

[Peter Ansell](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=p_ansell) you're right - for me snapshot version (r1801122) also works with Java 9 b175. Seems that this is a good side effect of [MJAVADOC-465]. And so indeed, [Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte), MJAVADOC-488 is not entirely duplicate of this. This also means that workaround for version 2.10.4 for Java 9 >= b175 is

```
<plugin>
  <groupId>org.apache.maven.plugins</groupId>
  <artifactId>maven-javadoc-plugin</artifactId>
  <version>2.10.4</version>
  <dependencies>
    <dependency>
      <groupId>commons-lang</groupId>
      <artifactId>commons-lang</artifactId>
      <version>2.6</version>
    </dependency>
  </dependencies>
</plugin>
```

HTH.

**Comment by jira-importer** [comment]
**[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte)** commented

Last commit drops all float-based version comparison, new implementation should be more reliable.
Patch is applied (thanks for that!), because moving to lang3 is a good thing.
Please verify.

**Comment by jira-importer** [comment]
**[Peter Ansell](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=p_ansell)** commented

Commons-lang:2.4 is still on the dependency list as a transitive dependency of doxia-site-renderer:1.7.4. This doesn't seem to be affecting the plugins functionality, so it doesn't seem necessary to keep this issue open and block a release, but commons-lang:2.4 will still be on the build path until doxia-site-renderer releases a new patched version.

Commons-lang3:3.5 also triggers the warning about illegal access to ArrayList.serialVersionUID (see my comment above), but updating to 3.6 (which may still have the same issue) isn't possible without tipping the delicate java-6/java-7 balance.

It looks like the javadoc is generated correctly when running it using JDK-9 (using my simple test project), so confirming that upgrading didn't break that core functionality.
