### ISSUE TITLE
[MJAVADOC-213] Unix Shell used is Configurable

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-javadoc-plugin#949]
**[John Patrick](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=nhoj.patrick)** opened **[MJAVADOC-213](https://issues.apache.org/jira/browse/MJAVADOC-213?redirect=false)** and commented

Not all linux enviroments have bash installed, configuration ability might be useful for the javadoc plugin.

Embedded error: Error rendering Maven report: Unable to find javadoc
version: Error while executing process.
/bin/bash: not found
[INFO]

---

[INFO] Trace
org.apache.maven.lifecycle.LifecycleExecutionException: Error during
page generation
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:583)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:499)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:478)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:330)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:291)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:142)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:336)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:129)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:287)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:324)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
Caused by: org.apache.maven.plugin.MojoExecutionException: Error during
page generation
at org.apache.maven.plugins.site.SiteMojo.execute(SiteMojo.java:101)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:451)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:558)
... 16 more
Caused by: org.apache.maven.doxia.siterenderer.RendererException: Error
rendering Maven report: Unable to find javadoc version: Error while
executing process.
at org.apache.maven.plugins.site.ReportDocumentRenderer.renderDocument(ReportDocumentRenderer.java:149)
at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.renderModule(DefaultSiteRenderer.java:269)
at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.render(DefaultSiteRenderer.java:101)
at org.apache.maven.plugins.site.SiteMojo.renderLocale(SiteMojo.java:129)
at org.apache.maven.plugins.site.SiteMojo.execute(SiteMojo.java:96)
... 18 more
Caused by: org.apache.maven.reporting.MavenReportException: Unable to
find javadoc version: Error while executing process.
at org.apache.maven.plugin.javadoc.AbstractJavadocMojo.executeReport(AbstractJavadocMojo.java:1093)
at org.apache.maven.plugin.javadoc.JavadocReport.generate(JavadocReport.java:131)
at org.apache.maven.plugins.site.ReportDocumentRenderer.renderDocument(ReportDocumentRenderer.java:139)
... 22 more
Caused by: org.codehaus.plexus.util.cli.CommandLineException: Error
while executing process.
at org.codehaus.plexus.util.cli.Commandline.execute(Commandline.java:652)
at org.codehaus.plexus.util.cli.CommandLineUtils.executeCommandLine(CommandLineUtils.java:102)
at org.codehaus.plexus.util.cli.CommandLineUtils.executeCommandLine(CommandLineUtils.java:89)
at org.apache.maven.plugin.javadoc.AbstractJavadocMojo.getJavadocVersion(AbstractJavadocMojo.java:2941)
at org.apache.maven.plugin.javadoc.AbstractJavadocMojo.executeReport(AbstractJavadocMojo.java:1085)
... 24 more
Caused by: java.io.IOException: /bin/bash: not found
at java.lang.UNIXProcess.forkAndExec(Native Method)
at java.lang.UNIXProcess.&lt;init&gt;(UNIXProcess.java:52)
at java.lang.Runtime.execInternal(Native Method)
at java.lang.Runtime.exec(Runtime.java:566)
at org.codehaus.plexus.util.cli.Commandline.execute(Commandline.java:647)
... 28 more
[INFO]

---

[INFO] Total time: 26 seconds
[INFO] Finished at: Wed Aug 20 15:17:12 CEST 2008
[INFO] Final Memory: 44M/83M
[INFO]

---

---

**Affects:** 2.4

**Comment by jira-importer** [comment]
**[Olivier Lamy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=olamy)** commented

This should be fixed : see MJAVADOC-154.
Have you lock the javadoc plugin version in your pom ?

**Comment by jira-importer** [comment]
**[Ringo De Smet](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ringods)** commented

Olivier,

Yes, I had locked maven-javadoc-plugin to 2.3. Version 2.4 seems to resolve the issue. Sorry for the overhead. This issue may be closed.

Ringo
