### ISSUE TITLE
[MJAVADOC-214] test javadoc goal uses incorrect dependency classpath

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-javadoc-plugin#973]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** opened **[MJAVADOC-214](https://issues.apache.org/jira/browse/MJAVADOC-214?redirect=false)** and commented

according to this report: http://www.nabble.com/JavaDoc-Report-crashes-with-TestNG-tp19139379p19158787.html

The test javadoc goal is not using the test classpath dependencies.

---

**Affects:** 2.4

4 votes, 6 watchers

**Comment by jira-importer** [comment]
**[Tan Quach](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=tquach)** commented

I am getting these same errors, however here is some additional information:

When I run "mvn javadoc:test-javadoc" from within either a standalone project or sub-module project that has test sources, it works fine.

When I run "mvn javadoc:test-javadoc" from a parent project, it fails when it gets to the sub-module.

**Comment by jira-importer** [comment]
**[Siveton Vincent](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=siveton)** commented

Since I am unable to reproduce it, I need a test case.

> When I run "mvn javadoc:test-javadoc" from a parent project, it fails when it gets to the sub-module.

Could you try with javadoc:test-aggregate (introduced in Javadoc plugin 2.5)

**Comment by jira-importer** [comment]
**[Chris Wilper](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cwilper)** commented

I had the same problem (also present when aggregate=true), and it went away when upgrading to 2.5

**Comment by jira-importer** [comment]
**[Rodolfo Rothganger](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rothganger)** commented

I´ve got a similar problems regarding annotations not found by the plugin. In my project there is a parent POM declaring FindBugs annotations as "compile" scoped dependencies.

While tring to deploy an artifact with the above POM as parent  produced the following error:

"
a "java.lang.ClassCastException: com.sun.tools.javadoc.ClassDocImpl cannot be cast to com.sun.javadoc.AnnotationTypeDoc
at com.sun.tools.javadoc.AnnotationDescImpl.annotationType(AnnotationDescImpl.java:46)
at com.sun.tools.doclets.internal.toolkit.util.Util.isDeprecated(Util.java:811)
"

To work around the problem I´ve declared the compile scoped annotations as dependencies of the plugin itself.

**Comment by jira-importer** [comment]
**[Christian Decker](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cdecker)** commented

How would you do that?

**Comment by jira-importer** [comment]
**[Roger Deloy Pack](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rogerpack)** commented

for 2.4:

\<dependency>
\<groupId>org.testng\</groupId>
\<artifactId>testng\</artifactId>
\<version>5.8\</version>
\<classifier>jdk15\</classifier>
\
\</dependency>

**Comment by jira-importer** [comment]
**[Josh Devins](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jdevins)** commented

Just a confirmation that I also encountered this problem with version 2.4, but since upgrading to 2.5 it seems to work fine. The project structure where I saw this was perhaps the problem. It looked like this:

project/pom.xml <-- this is where I would run from to reproduce the problem
project/project-parentPom/pom.xml <-- the parent pom was a module of the "root" project pom
project/project-anotherArtifact/pom.xml <-- this is where the failure was occurring for test dependencies

But as I mentioned, upgrading to 2.5 solved the problem for this project and structure (although I don't advocate using such a project structure!).

**Comment by jira-importer** [comment]
**[Siveton Vincent](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=siveton)** commented

Seems to be fix somewhere between 2.4 and 2.6...

**Comment by jira-importer** [comment]
**[Francis De Brabandere](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=francisdb)** commented

I have seen this issue when you do a "mvn clean install site" on a multimodule build where javadoc report aggregation is enabled. And this only after changing to a new version. (it's indicated in the logs that he does not seem to find snapshots)
The fix was to do a "mvn clean install" first to get the snapshots in the local repo or to disable report generation.
