### ISSUE TITLE
[MJAVADOC-224] CLONE -If Javadoc is set to aggregate, the build fails inside a Maven plugin module

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-javadoc-plugin#997]
**[Christian Schulte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=schulte77)** opened **[MJAVADOC-224](https://issues.apache.org/jira/browse/MJAVADOC-224?redirect=false)** and commented

If your project contains a Maven plugin, then it is impossible to build aggregated Javadoc.

As the output (attached) shows, Maven seems to recusively build (what's with all those "skipping" messages?).  When it reaches the plugin:

[INFO] Error during page generation

Embedded error: Error rendering Maven report: Error extracting plugin descriptor: 'Goal: component-report already exists in the plugin descriptor for prefix: tapestry-component-report
Existing implementation is: org.apache.tapestry.mojo.ComponentReport
Conflicting implementation is: org.apache.tapestry.mojo.ComponentReport'

I  can get by this with the -fn (fail never) option.

---

**Affects:** 2.3

**Issue Links:**
- [MJAVADOC-145](https://issues.apache.org/jira/browse/MJAVADOC-145) If Javadoc is set to aggregate, the build fails inside a Maven plugin module
 (_**"is duplicated by"**_)

**Comment by jira-importer** [comment]
**[Christian Schulte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=schulte77)** commented

Having

```xml
<reporting>
  <plugins>
    <plugin>
      <groupId>org.apache.maven.plugins</groupId>
      <artifactId>maven-javadoc-plugin</artifactId>
      <version>2.5</version>
      <reportSets>
        <reportSet>
          <id>javadoc</id>
          <inherited>true</inherited>
          <reports>
            <report>javadoc</report>
          </reports>
          <configuration>
            <aggregate>false</aggregate>
            <author>true</author>
            <charset>UTF-8</charset>
            <docencoding>UTF-8</docencoding>
            <encoding>UTF-8</encoding>
            <keywords>true</keywords>
            <doctitle>${pom.name} Specification ${pom.version}</doctitle>
            <linksource>true</linksource>
            <nodeprecated>true</nodeprecated>
            <quiet>false</quiet>
            <verbose>false</verbose>
            <serialwarn>true</serialwarn>
            <windowtitle>${pom.name} Specification ${pom.version}</windowtitle>
            <overview>${basedir}/src/main/javadoc/overview.html</overview>
            <show>public</show>
            <links>
              <link>http://java.sun.com/j2se/1.5.0/docs/api</link>
            </links>
          </configuration>
        </reportSet>
        <reportSet>
          <id>aggregate</id>
          <inherited>false</inherited>
          <reports>
            <report>aggregate</report>
          </reports>
          <configuration>
            <aggregate>true</aggregate>
            <breakiterator>true</breakiterator>
            <charset>UTF-8</charset>
            <docencoding>UTF-8</docencoding>
            <encoding>UTF-8</encoding>
            <keywords>false</keywords>
            <linksource>true</linksource>
            <serialwarn>true</serialwarn>
            <show>private</show>
            <doctitle>${pom.name} Specification ${pom.version}</doctitle>
            <windowtitle>${pom.name} Specification ${pom.version}</windowtitle>
          </configuration>
        </reportSet>
      </reportSets>
    </plugin>
```

in a parent pom from a multi-module project containing a mojo artifact defined like

```java
* @goal java-resources
* @phase generate-sources
* @requiresDependencyResolution compile
```

still produces a similar stacktrace for me

```java
[INFO] Trace
org.apache.maven.lifecycle.LifecycleExecutionException: Error extracting plugin descriptor: 'Goal: java-resources already exists in the plugin descriptor for prefix: some-prefix
Existing implementation is: some.package.JavaResourcesMojo
Conflicting implementation is: some.package.JavaResourcesMojo'
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:583)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:499)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.forkProjectLifecycle(DefaultLifecycleExecutor.java:924)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.forkLifecycle(DefaultLifecycleExecutor.java:767)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:549)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeStandaloneGoal(DefaultLifecycleExecutor.java:512)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:482)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:330)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:291)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:142)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:336)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:129)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:287)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:324)
        at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
        at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
        at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
        at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
Caused by: org.apache.maven.plugin.MojoExecutionException: Error extracting plugin descriptor: 'Goal: java-resources already exists in the plugin descriptor for prefix: some-prefix
Existing implementation is: some.package.JavaResourcesMojo
Conflicting implementation is: some.package.JavaResourcesMojo'
        at org.apache.maven.plugin.plugin.AbstractGeneratorMojo.execute(AbstractGeneratorMojo.java:158)
        at org.apache.maven.plugin.plugin.HelpGeneratorMojo.execute(HelpGeneratorMojo.java:63)
        at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:451)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:558)
        ... 20 more
Caused by: org.apache.maven.plugin.descriptor.DuplicateMojoDescriptorException: Goal: java-resources already exists in the plugin descriptor for prefix: some-prefix
Existing implementation is: some.package.JavaResourcesMojo
Conflicting implementation is: some.package.JavaResourcesMojo
        at org.apache.maven.plugin.descriptor.PluginDescriptor.addMojo(PluginDescriptor.java:103)
        at org.apache.maven.tools.plugin.scanner.DefaultMojoScanner.populatePluginDescriptor(DefaultMojoScanner.java:110)
        at org.apache.maven.plugin.plugin.AbstractGeneratorMojo.execute(AbstractGeneratorMojo.java:146)
        ... 23 more

```

when executing

```java
mvn site:stage -DstagingDirectory=/tmp/staging -e
```

**Comment by jira-importer** [comment]
**[Siveton Vincent](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=siveton)** commented

It seems to not be a bug into the javadoc plugin but I guess that you defined 2 mojos with same goal...

**Comment by jira-importer** [comment]
**[rt15](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rt15)** commented

Taking exactly the same issue...

(Project with multiple modules and a plugin, agregate with javadoc in version 2.5 -> goal already exists)

Maybe more info later.

**Comment by jira-importer** [comment]
**[rt15](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rt15)** commented

org.apache.maven.plugins:maven-javadoc-plugin:2.5:aggregate
-> error

org.apache.maven.plugins:maven-javadoc-plugin:2.2:javadoc
-> works fine

Other topics on the subject :
http://mail-archives.apache.org/mod_mbox/maven-doxia-dev/200709.mbox/%3C46E37CCE.5080202@apache.org%3E
http://jira.codehaus.org/browse/MJAVADOC-145
http://www.nabble.com/%22Goal:-clean-already-exists-in-the-plugin-descriptor-for-prefix:-...%22-td23127658.html

**Comment by jira-importer** [comment]
**[Jean-Claude Rouvinez](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jcrouvi@yahoo.com)** commented

I experience the same phenomenon with \<artifactId>maven-javadoc-plugin\</artifactId> \<version>2.6\</version> and I haven't set the 'agregate' property (default is false).
If I go back to \<version>2.2\</version> everything is alright.

Here a part of the file pom.xml:

    <plugin>
      <groupId>org.apache.maven.plugins</groupId>
      <artifactId>maven-javadoc-plugin</artifactId>
      <version>2.2</version>
      <configuration>
        <quiet>true</quiet>
        <show>protected</show>
        <links>
          <link>http://java.sun.com/javase/6/docs/api/</link>
          <link>http://java.sun.com/javaee/5/docs/api/</link>
        </links>
      </configuration>
    </plugin>

**Comment by jira-importer** [comment]
**[Jean-Claude Rouvinez](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jcrouvi@yahoo.com)** commented

According to the comment above (jcrouvi added a comment - 24/Aug/09 06:18 AM) this bug should be reopened.

**Comment by jira-importer** [comment]
**[Toni Menzel](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=tonit)** commented

+1 for re-opening this. We have failed site + releasebuilds when using maven-javadoc-plugin 2.4 + 2.5 in combination with mojos.
Going back to 2.2 is a (temporary) solution.

**Comment by jira-importer** [comment]
**[Ceki Gülcü](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ceki@qos.ch)** commented

An open source project of ours uses aggregated javadocs. See [1]. Moving to maven-javadoc-plugin 2.2 solved it for us.

[1] http://cal10n.qos.ch/

**Comment by jira-importer** [comment]
**[Jean-Claude Rouvinez](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jcrouvi@yahoo.com)** commented

Issue http://jira.codehaus.org/browse/MJAVADOC-257 added
