### ISSUE TITLE
[MJAVADOC-238] No timeout set for URLConnection which can cause build to get stuck

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-javadoc-plugin#998]
**[syvalta](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=syvalta)** opened **[MJAVADOC-238](https://issues.apache.org/jira/browse/MJAVADOC-238?redirect=false)** and commented

I encountered a release build getting stuck. Stack trace revealed that the culprit was an infinite default timeout in URLConnection.

[INFO] 	at java.net.URL.openStream(URL.java:1007)
[INFO] 	at org.apache.maven.plugin.javadoc.JavadocUtil.fetchURL(JavadocUtil.java:742)
[INFO] 	at org.apache.maven.plugin.javadoc.AbstractJavadocMojo.addLinkArguments(AbstractJavadocMojo.java:2982)
[INFO] 	at org.apache.maven.plugin.javadoc.AbstractJavadocMojo.addStandardDocletOptions(AbstractJavadocMojo.java:3667)
[INFO] 	at org.apache.maven.plugin.javadoc.AbstractJavadocMojo.executeReport(AbstractJavadocMojo.java:1548)
[INFO] 	at org.apache.maven.plugin.javadoc.JavadocJar.execute(JavadocJar.java:182)
[INFO] 	at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:483)

The simple fix is to call setConnectTimeout and setReadTimeout with some sensible default value (jdk 1.5 methods, so might need to use reflection to preseve jdk 1.4 compatibility).

---

**Affects:** 2.5

**Comment by jira-importer** [comment]
**[Siveton Vincent](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=siveton)** commented

Fixed in [r793854](http://svn.apache.org/viewvc?rev=793854&view=rev), snapshot deployed
Please test it so I could close it.

**Comment by jira-importer** [comment]
**[Siveton Vincent](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=siveton)** commented

I added more tests in [r797750](http://svn.apache.org/viewvc?rev=797750&view=rev). All sounds good.
